CREATE TABLE "line_score" (
  "game_sequence" INTEGER,
  "game_id" int,
  "team_id_home" int,
  "team_wins_losses_home" TEXT,
  "pts_qtr1_home" INTEGER,
  "pts_qtr2_home" INTEGER,
  "pts_qtr3_home" INTEGER,
  "pts_qtr4_home" INTEGER,
  "pts_ot1_home" INTEGER,
  "pts_ot2_home" INTEGER,
  "pts_ot3_home" INTEGER,
  "pts_ot4_home" INTEGER,
  "pts_ot5_home" INTEGER,
  "pts_ot6_home" INTEGER,
  "pts_ot7_home" INTEGER,
  "pts_ot8_home" INTEGER,
  "pts_ot9_home" INTEGER,
  "pts_ot10_home" INTEGER,
  "pts_home" REAL,
  "team_id_away" TEXT,
  "team_wins_losses_away" TEXT,
  "pts_qtr1_away" INTEGER,
  "pts_qtr2_away" INTEGER,
  "pts_qtr3_away" INTEGER,
  "pts_qtr4_away" INTEGER,
  "pts_ot1_away" INTEGER,
  "pts_ot2_away" INTEGER,
  "pts_ot3_away" INTEGER,
  "pts_ot4_away" INTEGER,
  "pts_ot5_away" INTEGER,
  "pts_ot6_away" INTEGER,
  "pts_ot7_away" INTEGER,
  "pts_ot8_away" INTEGER,
  "pts_ot9_away" INTEGER,
  "pts_ot10_away" INTEGER,
  "pts_away" REAL
);

CREATE TABLE "play_by_play" (
  "game_id" int,
  "eventnum" INTEGER,
  "eventmsgtype" INTEGER,
  "eventmsgactiontype" INTEGER,
  "period" INTEGER,
  "wctimestring" TEXT,
  "pctimestring" TEXT,
  "homedescription" TEXT,
  "neutraldescription" TEXT,
  "visitordescription" TEXT,
  "score" TEXT,
  "scoremargin" TEXT,
  "person1type" REAL,
  "player1_id" int,
  "player1_team_id" int,
  "person2type" REAL,
  "player2_id" int,
  "player2_team_id" int,
  "person3type" REAL,
  "player3_id" int,
  "player3_team_id" int,
  "video_available_flag" TEXT
);

CREATE TABLE "other_stats" (
  "game_id" int,
  "league_id" int,
  "team_id_home" int,
  "pts_paint_home" INTEGER,
  "pts_2nd_chance_home" INTEGER,
  "pts_fb_home" INTEGER,
  "largest_lead_home" INTEGER,
  "lead_changes" INTEGER,
  "times_tied" INTEGER,
  "team_turnovers_home" INTEGER,
  "total_turnovers_home" INTEGER,
  "team_rebounds_home" INTEGER,
  "pts_off_to_home" INTEGER,
  "team_id_away" int,
  "pts_paint_away" INTEGER,
  "pts_2nd_chance_away" INTEGER,
  "pts_fb_away" INTEGER,
  "largest_lead_away" INTEGER,
  "team_turnovers_away" INTEGER,
  "total_turnovers_away" INTEGER,
  "team_rebounds_away" INTEGER,
  "pts_off_to_away" INTEGER
);

CREATE TABLE "game_summary" (
  "game_date_est" TIMESTAMP,
  "game_sequence" INTEGER,
  "game_id" int,
  "game_status_id" INTEGER,
  "game_status_text" TEXT,
  "gamecode" TEXT,
  "home_team_id" int,
  "visitor_team_id" int,
  "season" int,
  "live_period" INTEGER,
  "live_pc_time" TEXT,
  "natl_tv_broadcaster_abbreviation" TEXT,
  "live_period_time_bcast" TEXT,
  "wh_status" INTEGER
);

CREATE TABLE "inactive_players" (
  "game_id" int,
  "player_id" int,
  "jersey_num" TEXT,
  "team_id" int
);

CREATE TABLE "officials" (
  "official_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "first_name" TEXT,
  "last_name" TEXT,
  "jersey_num" TEXT
);

CREATE TABLE "official_of_game" (
  "game_id" int,
  "official_id" int
);

CREATE TABLE "season_type" (
  "season_type_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "season_type" TEXT
);

CREATE TABLE "game" (
  "season_id" int,
  "team_id_home" int,
  "game_id" int,
  "matchup_home" TEXT,
  "wl_home" TEXT,
  "min" INTEGER,
  "fgm_home" REAL,
  "fga_home" REAL,
  "fg_pct_home" REAL,
  "fg3m_home" REAL,
  "fg3a_home" REAL,
  "fg3_pct_home" REAL,
  "ftm_home" REAL,
  "fta_home" REAL,
  "ft_pct_home" REAL,
  "oreb_home" REAL,
  "dreb_home" REAL,
  "reb_home" REAL,
  "ast_home" REAL,
  "stl_home" REAL,
  "blk_home" REAL,
  "tov_home" REAL,
  "pf_home" REAL,
  "pts_home" REAL,
  "plus_minus_home" INTEGER,
  "video_available_home" INTEGER,
  "team_id_away" int,
  "matchup_away" TEXT,
  "wl_away" TEXT,
  "fgm_away" REAL,
  "fga_away" REAL,
  "fg_pct_away" REAL,
  "fg3m_away" REAL,
  "fg3a_away" REAL,
  "fg3_pct_away" REAL,
  "ftm_away" REAL,
  "fta_away" REAL,
  "ft_pct_away" REAL,
  "oreb_away" REAL,
  "dreb_away" REAL,
  "reb_away" REAL,
  "ast_away" REAL,
  "stl_away" REAL,
  "blk_away" REAL,
  "tov_away" REAL,
  "pf_away" REAL,
  "pts_away" REAL,
  "plus_minus_away" INTEGER,
  "video_available_away" INTEGER,
  "season_type_id" INT
);

CREATE TABLE "game_attendance" (
  "game_id" int,
  "attendance" INTEGER,
  "game_time" TEXT
);

CREATE TABLE "game_date" (
  "game_id" int,
  "game_date" TIMESTAMP
);

CREATE TABLE "game_info" (
  "game_id" TEXT UNIQUE PRIMARY KEY
);

CREATE TABLE "draft_combine_stats" (
  "season" int,
  "player_id" int,
  "position_id" int,
  "height_wo_shoes" REAL,
  "height_wo_shoes_ft_in" TEXT,
  "height_w_shoes" REAL,
  "height_w_shoes_ft_in" TEXT,
  "weight" TEXT,
  "wingspan" REAL,
  "wingspan_ft_in" TEXT,
  "standing_reach" REAL,
  "standing_reach_ft_in" TEXT,
  "body_fat_pct" TEXT,
  "hand_length" TEXT,
  "hand_width" TEXT,
  "standing_vertical_leap" REAL,
  "max_vertical_leap" REAL,
  "lane_agility_time" REAL,
  "modified_lane_agility_time" REAL,
  "three_quarter_sprint" REAL,
  "bench_press" REAL,
  "spot_fifteen_corner_left" TEXT,
  "spot_fifteen_break_left" TEXT,
  "spot_fifteen_top_key" TEXT,
  "spot_fifteen_break_right" TEXT,
  "spot_fifteen_corner_right" TEXT,
  "spot_college_corner_left" TEXT,
  "spot_college_break_left" TEXT,
  "spot_college_top_key" TEXT,
  "spot_college_break_right" TEXT,
  "spot_college_corner_right" TEXT,
  "spot_nba_corner_left" TEXT,
  "spot_nba_break_left" TEXT,
  "spot_nba_top_key" TEXT,
  "spot_nba_break_right" TEXT,
  "spot_nba_corner_right" TEXT,
  "off_drib_fifteen_break_left" TEXT,
  "off_drib_fifteen_top_key" TEXT,
  "off_drib_fifteen_break_right" TEXT,
  "off_drib_college_break_left" TEXT,
  "off_drib_college_top_key" TEXT,
  "off_drib_college_break_right" TEXT,
  "on_move_fifteen" TEXT,
  "on_move_college" TEXT
);

CREATE TABLE "position" (
  "position_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "position" TEXT
);

CREATE TABLE "last_affiliation" (
  "last_affiliation_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "last_affiliation" TEXT
);

CREATE TABLE "country" (
  "country_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "country" TEXT
);

CREATE TABLE "school" (
  "school_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "school" TEXT
);

CREATE TABLE "common_player_info" (
  "person_id" int,
  "display_fi_last" TEXT,
  "player_slug" TEXT,
  "birthdate" TIMESTAMP,
  "country_id" INT,
  "last_affiliation_id" int,
  "height" TEXT,
  "weight" TEXT,
  "season_exp" REAL,
  "jersey" TEXT,
  "position_id" int,
  "rosterstatus" TEXT,
  "games_played_current_season_flag" TEXT,
  "team_id" INTEGER,
  "playercode" TEXT,
  "from_year" REAL,
  "to_year" REAL,
  "dleague_flag" TEXT,
  "nba_flag" TEXT,
  "games_played_flag" TEXT,
  "draft_year" TEXT,
  "draft_round" TEXT,
  "draft_number" TEXT,
  "greatest_75_flag" TEXT
);

CREATE TABLE "player_school" (
  "school_id" int,
  "person_id" TEXT
);

CREATE TABLE "draft" (
  "draft_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "draft_type" TEXT
);

CREATE TABLE "Organization_type" (
  "organization_type_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "organization_type" TEXT
);

CREATE TABLE "Organization" (
  "organization_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "organization" TEXT,
  "organization_type_id" int
);

CREATE TABLE "draft_history" (
  "person_id" int,
  "season" integer,
  "round_number" INTEGER,
  "round_pick" INTEGER,
  "overall_pick" INTEGER,
  "draft_id" int,
  "team_id" int,
  "organization_id" int,
  "player_profile_flag" int
);

CREATE TABLE "player_active" (
  "id" int,
  "s_active" INTEGER
);

CREATE TABLE "team_details" (
  "team_id" int,
  "arena" TEXT,
  "arenacapacity" REAL,
  "owner" TEXT,
  "generalmanager" TEXT,
  "headcoach" TEXT,
  "dleagueaffiliation" TEXT,
  "facebook" TEXT,
  "instagram" TEXT,
  "twitter" TEXT
);

CREATE TABLE "team_history" (
  "team_id" int,
  "year_active_till" INTEGER
);

CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "city" TEXT
);

CREATE TABLE "states" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "state" TEXT
);

CREATE TABLE "team" (
  "id" int UNIQUE PRIMARY KEY,
  "full_name" TEXT,
  "abbreviation" TEXT,
  "nickname" TEXT,
  "city" int,
  "state" int,
  "year_founded" REAL
);

CREATE TABLE "player" (
  "id" int UNIQUE PRIMARY KEY,
  "first_name" TEXT,
  "last_name" TEXT
);

ALTER TABLE "team" ADD FOREIGN KEY ("city") REFERENCES "cities" ("id");

ALTER TABLE "team" ADD FOREIGN KEY ("state") REFERENCES "states" ("id");

ALTER TABLE "team_history" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "team_details" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "player_active" ADD FOREIGN KEY ("id") REFERENCES "player" ("id");

ALTER TABLE "draft_history" ADD FOREIGN KEY ("person_id") REFERENCES "player" ("id");

ALTER TABLE "draft_history" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "common_player_info" ADD FOREIGN KEY ("person_id") REFERENCES "player" ("id");

ALTER TABLE "common_player_info" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "draft_combine_stats" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("team_id_home") REFERENCES "team" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("team_id_away") REFERENCES "team" ("id");

ALTER TABLE "game_attendance" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "game" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "game_date" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "official_of_game" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "official_of_game" ADD FOREIGN KEY ("official_id") REFERENCES "officials" ("official_id");

ALTER TABLE "inactive_players" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "inactive_players" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "game_summary" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "game_summary" ADD FOREIGN KEY ("home_team_id") REFERENCES "team" ("id");

ALTER TABLE "game_summary" ADD FOREIGN KEY ("visitor_team_id") REFERENCES "team" ("id");

ALTER TABLE "other_stats" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "other_stats" ADD FOREIGN KEY ("team_id_home") REFERENCES "team" ("id");

ALTER TABLE "other_stats" ADD FOREIGN KEY ("team_id_away") REFERENCES "team" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player1_id") REFERENCES "player" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player2_id") REFERENCES "player" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player3_id") REFERENCES "player" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player1_team_id") REFERENCES "team" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player2_team_id") REFERENCES "team" ("id");

ALTER TABLE "play_by_play" ADD FOREIGN KEY ("player3_team_id") REFERENCES "team" ("id");

ALTER TABLE "line_score" ADD FOREIGN KEY ("game_id") REFERENCES "game_info" ("game_id");

ALTER TABLE "line_score" ADD FOREIGN KEY ("team_id_home") REFERENCES "team" ("id");

ALTER TABLE "line_score" ADD FOREIGN KEY ("team_id_away") REFERENCES "team" ("id");

ALTER TABLE "draft_history" ADD FOREIGN KEY ("draft_id") REFERENCES "draft" ("draft_id");

ALTER TABLE "draft_history" ADD FOREIGN KEY ("organization_id") REFERENCES "Organization" ("organization_id");

ALTER TABLE "Organization" ADD FOREIGN KEY ("organization_type_id") REFERENCES "Organization_type" ("organization_type_id");

ALTER TABLE "player_school" ADD FOREIGN KEY ("person_id") REFERENCES "player" ("id");

ALTER TABLE "player_school" ADD FOREIGN KEY ("school_id") REFERENCES "school" ("school_id");

ALTER TABLE "common_player_info" ADD FOREIGN KEY ("country_id") REFERENCES "country" ("country_id");

ALTER TABLE "common_player_info" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("position_id");

ALTER TABLE "common_player_info" ADD FOREIGN KEY ("last_affiliation_id") REFERENCES "last_affiliation" ("last_affiliation_id");

ALTER TABLE "draft_combine_stats" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("position_id");

ALTER TABLE "game" ADD FOREIGN KEY ("season_type_id") REFERENCES "season_type" ("season_type_id");

ALTER TABLE public.team ADD COLUMN team_code TEXT;

ALTER TABLE public.player_school
DROP COLUMN person_id;
ALTER TABLE public.player_school
ADD COLUMN person_id INT;

ALTER TABLE public.player_school
ADD CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.player(id);